repository_type: pipeline

lint:
    files_exist:
        - conf/igenomes.config
    files_unchanged:
        - .github/workflows/branch.yml
        - .github/workflows/linting_comment.yml
        - .github/workflows/linting.yml
